name: Build Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Capacitor CLI & Tools
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli
          npx cap init "Bijoy Converter Pro" "com.nibrasit.bijoyconverter" --web-dir=.
          npm install @capacitor/android
          npx cap add android

      - name: Sync Web Code with Android
        run: npx cap sync

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android APK (Release & Debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Bijoy-Converter-Pro-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
